### ISSUE TITLE
packages are not found

### ISSUE THREAD

**Issue by LiQinYale** [huangrh/rstarating#1]
When I tried to run
> devtools::install_github("huangrh/rstarating");
> devtools::install_github("huangrh/relvm");

I was told that packages 'rstarrating' and 'relvm' are not found. Are they removed?
Thank you!

**Comment by huangrh** [comment]
Hi LIQin, 

I just tested the installations and it works. 
I guess you probably have issues with "devtools" package. 

I suggest you update the "devtools" package by running the following within R :
> devtools::install_github("hadley/devtools") 

and then test your installation.
> devtools::has_devel()  # should return TRUE. 

Let me know if this fixed your problem.
Thanks,

Ren-Huai 
Ascension

**Comment by LiQinYale** [comment]
The problem is solved. Thank you for your quick reply.

Best,
Li
