### ISSUE TITLE
Trouble installing devtools::install_github("huangrh/relvm");

### ISSUE THREAD

**Issue by ghost** [huangrh/rstarating#2]
@huangrh First of all, thank you for putting this together! 

It looks like I'm getting the below error when trying to install the "relvm" package. It looks like there is a dependency missing called "pracma?"

> devtools::install_github("huangrh/relvm");
Downloading GitHub repo huangrh/relvm@master
from URL https://api.github.com/repos/huangrh/relvm/zipball/master
Installing relvm
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Carmijh0/AppData/Local/Temp/Rtmp6vT7TU/devtools317c31d86dde/huangrh-relvm-8b3a1e2"  \
  --library="C:/Users/Carmijh0/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'relvm' ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'pracma'
ERROR: lazy loading failed for package 'relvm'
* removing 'C:/Users/Carmijh0/Documents/R/win-library/3.4/relvm'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by huangrh** [comment]
Thank you for your interesting. I just updated the package dependency description. Let me if you still have issues or any questions. 

Have a nice weekend. 

Ren-Huai Huang

**Comment by ghost** [comment]
@huangrh Thanks so much for updating the dependencies! One more question for you. 

Do you know if the relvm_quad (Gaussian quadrature approximation with 30 qpoints) can be run to exactly replicate the 2016 CMS results? It looks like I'm getting an Error ("Error in relvm_quad(x) : could not find function "relvm_quad") when trying to run the lvm. 

Thanks for your time.

**Comment by huangrh** [comment]
Hi, 
The 'relvm_quad' have been renamed to "relvm_noad" to match the meaning of non-adaptive. And you should reinstall all three programs, which take care of some default parameters during the rating process,  in order to replicate CMS hospital overall rating from Oct. 2016.  Sorry for the delay due to very busy. I will close this installation issue. Please open a new one if you have any other questions. 

Thanks!
