### ISSUE TITLE
Errors in installing the package

### ISSUE THREAD

**Issue by sanokaz368** [huangrh/rstarating#4]
I tried to install the packages "rstarating" and "relvm", but the following errors appeared. I would appreciate it if you could tell me how to deal with this error.

Error in eval(exprs[i], envir) : object 'pipe' not found
Error: unable to load R code in package 'rstarating'
Execution halted
ERROR: lazy loading failed for package 'rstarating'

**Comment by huangrh** [comment]
Install magrittr might fix the problem. 
> install.packages("magrittr")  

By the way, the logic used in the package is based on the CMS star rating from 2016 and CMS has updated since then .

**Comment by sanokaz368** [comment]
Thank you for your response. I have installed magrittr (2.0.3), but still the same errors appear. 

I want to replicate the CMS star rating using the CMS methodology at that time (December 2017).

**Comment by huangrh** [comment]
I think there is an issue with magrittr::pipe and it has been fixed. Please try again.

**Comment by sanokaz368** [comment]
Thank you very much for your trouble. I succeeded in installing the packages.
